config/routes.rb
Bone::Application.routes.draw do
  get "category/map"
  match "category/:name" => 'category#show'

  root :to =>  "home#index"

  
  resources :users
  resources :brands
  resources :categories
  resources :products

  match 'signin' => 'session#new'
  match 'signout' => 'session#destroy'
  match 'signup' => 'register#new'
  match 'auth' => 'session#create'
  match 'register/create' => 'register#create'
  match 'profile' => 'register#profile'
  match 'edit_profile' => 'register#edit_profile'
  match 'update_profile' => 'register#update_profile'

  get "static_page/about"
  get "static_page/contact"

end

app/models/brand.rb
# encoding : utf-8
require 'carrierwave/orm/activerecord'
class Brand < ActiveRecord::Base
  include CarrierWave::MiniMagick

  attr_accessible :description, :logo, :name, :summary, :logo_cache, :categories, :category_ids, :alias, :keywords

  mount_uploader :logo, LogoUploader

  has_and_belongs_to_many :categories

  validates :name, :uniqueness => {:message => '品牌已经存在'}, :presence => { :message => '请填写用户名'}, :length => {:to_long => "品牌名称不能超过%{count}个字符", :maximum => 64,  :minimum   => 1, :too_short => "品牌名称太短了喔"}
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  include SessionHelper
  before_filter :require_signed_in
  before_filter :require_admin

  # GET /brands
  # GET /brands.json
  def index
    #@brands = Brand.all
    @q = Brand.search(params[:q])
    @brands = @q.result(:distinct => true).paginate(:per_page => 15, :page => params[:page]).order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.haml
= simple_form_for(@brand, :html => {:class => 'form-horizontal', :multipart => true}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, :label => '品牌名称'
    = f.input :alias, :label => '别名'
    = f.input :keywords, :label => '关键字', :input_html => {:size => 256, :class => 'input-xxlarge'}
    = f.input :logo, :as => :image_preview, :input_html => {:preview_version => :thumb}
    = f.input :logo_cache, :as => 'hidden'
    = f.input :summary, :label => '简介', :input_html => {:rows => 5}
    = f.input :description, :label => '详细介绍', :input_html => {:rows => 10}
    = f.association :categories,  :as => :check_boxes, :label => '分类'

  .form-actions
    = f.button :submit, :value => '保存'

app/views/brands/edit.html.haml
.page-header
  %h4 修改 品牌

= render 'form'

= link_to '展示', @brand, :class => 'btn btn-mini btn-success'
\|
= link_to '返回', brands_path, :class => 'btn btn-mini'

app/views/brands/index.html.haml
.page-header
  %h4 品牌 列表

%table.table.table-bordered.table-striped
  %tr
    %th{:style => 'width:80px;'} Logo
    %th{:style => 'width:80px;'}
      =sort_link @q, :name, '品牌名称'
    %th{:style => 'width:80px;'}
      =sort_link @q, :alias, '别名'
    %th{:style => 'width:80px;'}
      =sort_link @q, :category_ids, '分类'
    %th{:style => 'width:300px;'}
      =sort_link @q, :keywords, '关键字'
    %th

  - @brands.each do |brand|
    %tr
      %td
        %img{:src => brand.logo.url}
      %td
        %small= brand.name
      %td
        %small= brand.alias
      %td 
        - brand.categories.each do |c|
          %small
            %a.pull_left{:href => category_path(c), :style => 'padding:0px 5px;'}= c.name
      %td
        %small=  brand.keywords
      %td 
        = link_to '展示', brand, :class => 'btn btn-mini'
        \|
        = link_to '修改', edit_brand_path(brand), :class => 'btn btn-mini btn-primary'
        \|
        = link_to '删除', brand, :method => :delete, :data => { :confirm => '你确定吗?' }, :class => 'btn btn-mini btn-danger'

%br
.pull-right= will_paginate @brands, :renderer => BootstrapPagination::Rails

= link_to '新增 品牌', new_brand_path, :class => 'btn btn-mini btn-success'

app/views/brands/new.html.haml
.page-header
  %h4 新增 品牌

= render 'form'

= link_to '返回', brands_path, :class => 'btn btn-mini'

app/views/brands/show.html.haml
.page-header
  展示

%p#notice= notice

%table.table.table-bordered
  %tr
    %th{:style => 'width:80px;'} 品牌名称
    %td= @brand.name
  %tr
    %th Logo
    %td
      %img{:src => @brand.logo.thumb}
  %tr
    %th 简介
    %td= @brand.summary.html_safe
  %tr
    %th 详细介绍
    %td= @brand.description.html_safe
  %tr
    %th 关键字
    %td= @brand.keywords


= link_to '修改', edit_brand_path(@brand), :class => 'btn btn-mini btn-primary'
\|
= link_to '返回', brands_path, :class => 'btn btn-mini'
\|
= link_to '新增 品牌', new_brand_path, :class => 'btn btn-mini btn-success'